"""New changes

Revision ID: 406311db384e
Revises: 7fbef6ac86cd
Create Date: 2024-09-18 13:11:51.583717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406311db384e'
down_revision: Union[str, None] = '7fbef6ac86cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the `available` column if it doesn't exist
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the `available` column during downgrade
    op.drop_column('books', 'available')
    # ### end Alembic commands ###
