"""CLI changes and added functionality

Revision ID: b92f45f82e82
Revises: 406311db384e
Create Date: 2024-09-18 16:54:49.029399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92f45f82e82'
down_revision: Union[str, None] = '406311db384e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     # Create a new table with the modified column (no NOT NULL constraint on 'available')
    op.create_table(
        'new_books',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('author', sa.String, nullable=False),
        sa.Column('available', sa.Integer, nullable=True),  # 'available' can now be NULL
        sa.Column('genres', sa.String, nullable=True)
    )
    
    # Copy data from the old 'books' table to the new one
    op.execute('''
        INSERT INTO new_books (id, title, author, available, genres)
        SELECT id, title, author, available, genres FROM books
    ''')

    # Drop the old 'books' table
    op.drop_table('books')

    # Rename the new table to 'books'
    op.rename_table('new_books', 'books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the original table (with NOT NULL constraint on 'available')
    op.create_table(
        'books',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('author', sa.String, nullable=False),
        sa.Column('available', sa.Integer, nullable=False),  # Original NOT NULL constraint
        sa.Column('genres', sa.String, nullable=True)
    )

    # Copy data back from 'new_books' to 'books'
    op.execute('''
        INSERT INTO books (id, title, author, available, genres)
        SELECT id, title, author, available, genres FROM new_books
    ''')

    # Drop the new_books table
    op.drop_table('new_books')
    # ### end Alembic commands ###
